gallery/urls.py
from django.urls import path

from . import views

app_name = 'gallery'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    # path('projects', views.projects, name='projects'),
    path('projects/', views.ProjectListView.as_view(), name='projects'),
    path('projects/project/<int:pk>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('projects/project/', views.project_detail, name='project_detail'),
]

serenitys_gallery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gallery.urls', namespace='gallery'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/models.py
from django.db import models

# Create your models here.

def picture_directory_path(instance, filename):
    if instance.design_type == Design.TWO_D:
        return 'designs/2d/{0}'.format(filename)
    elif instance.design_type == Design.THREE_D:
        return 'designs/3d/{0}'.format(filename)
    return 'designs/general/{0}'.format(filename)


class Design(models.Model):

    TWO_D = '2d'
    THREE_D = '2d'

    design_choices = (
        (TWO_D, '2D'),
        (THREE_D, '3D'),
    )

    name = models.CharField(max_length=30)
    caption = models.TextField()
    design_type = models.CharField(max_length=5, choices=design_choices)
    pic = models.ImageField(upload_to=picture_directory_path)
    # client = models.CharField(max_length=50)
    description = models.TextField()
    time_completed = models.DateField()

    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-timestamp']


class Message(models.Model):
    sender_name = models.CharField(max_length=100)
    sender_email = models.EmailField()
    subject = models.CharField(max_length=100)
    content = models.TextField()

    timestamp = models.DateTimeField(auto_now_add=True)
    sender_ip = models.GenericIPAddressField()

    def __str__(self):
        return self.sender_name

gallery/forms.py
from django import forms

from .models import Message


class MessageForm(forms.ModelForm):
    
    class Meta:
        model = Message
        fields = ("sender_name", "sender_email", "subject", "content")

        widgets = {
            'sender_name': forms.TextInput(attrs={'class': "form-control", 'placeholder': "Your Name"}),
            'sender_email': forms.EmailInput(attrs={'class': "form-control", 'placeholder': "Your Email"}),
            'subject': forms.TextInput(attrs={'class': "form-control", 'placeholder': "Subject"}),
            'content': forms.Textarea(attrs={'cols': 30, 'rows': 7, 'class': "form-control", 'placeholder': "Message"}),
        }

gallery/views.py
from django.shortcuts import render
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import ListView, DetailView, CreateView

from .forms import MessageForm
from .models import Design, Message


# Create your views here.

class ProjectListView(ListView):
    model = Design
    template_name = 'gallery/projects.html'
    paginate_by = 10


class ProjectDetailView(DetailView):
    model = Design
    template_name = 'gallery/project_details.html'


class ContactView(SuccessMessageMixin, CreateView):
    model = Message
    template_name = 'gallery/contact.html'
    form_class = MessageForm
    success_url = '/contact/'
    success_message = "Message successfully sent"

    def form_valid(self, form):
        form.instance.sender_ip = self.request.META['REMOTE_ADDR']
        return super(ContactView, self).form_valid(form)


def index(request):
    recent_designs = Design.objects.all()[:6]
    context = {
        'designs': recent_designs,
    }
    return render(request, 'gallery/index.html', context)


def about(request):
    return render(request, 'gallery/about.html')


def projects(request):
    return render(request, 'gallery/projects.html')


def project_detail(request):
    return render(request, 'gallery/project_details.html')


def contact(request):
    return render(request, 'gallery/contact.html')

gallery/templates/gallery/about.html
{% extends 'base/main.html' %}

{% load staticfiles %}

{% block nav-bar %}
<nav id="colorlib-main-menu" role="navigation">
    <ul>
        <li><a href="{% url 'gallery:index' %}">Home</a></li>
        <li><a href="{% url 'gallery:projects' %}">Portfolio</a></li>
        <li class="colorlib-active"><a href="{% url 'gallery:about' %}">About</a></li>
        <!-- <li><a href="">Services</a></li> -->
        <!-- <li><a href="blog.html">Blog</a></li> -->
        <li><a href="{% url 'gallery:contact' %}">Contact</a></li>
    </ul>
</nav>
{% endblock %}

{% block content %}
<div class="colorlib-about">
    <div class="colorlib-narrow-content">
        <div class="row row-bottom-padded-md">
            <div class="col-md-6">
                <div class="about-img animate-box" data-animate-effect="fadeInLeft" style="background-image: url({% static 'images/img_bg_2.jpg' %});">
                </div>
            </div>
            <div class="col-md-6 animate-box" data-animate-effect="fadeInLeft">
                <div class="about-desc">
                    <span class="heading-meta">Welcome</span>
                    <h2 class="colorlib-heading">Who we are</h2>
                    <p>On her way she met a copy. The copy warned the Little Blind Text, that where it came from it
                        would have been rewritten a thousand times and everything that was left from its origin would
                        be the word "and" and the Little Blind Text should turn around and return to its own, safe
                        country.</p>
                    <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It
                        is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
                </div>
                <div class="row padding">
                    <div class="col-md-4 no-gutters animate-box" data-animate-effect="fadeInLeft">
                        <a href="#" class="steps active">
                            <p class="icon"><span><i class="icon-check"></i></span></p>
                            <h3>We are <br>pasionate</h3>
                        </a>
                    </div>
                    <div class="col-md-4 no-gutters animate-box" data-animate-effect="fadeInLeft">
                        <a href="#" class="steps">
                            <p class="icon"><span><i class="icon-check"></i></span></p>
                            <h3>Honest <br>Dependable</h3>
                        </a>
                    </div>
                    <div class="col-md-4 no-gutters animate-box" data-animate-effect="fadeInLeft">
                        <a href="#" class="steps">
                            <p class="icon"><span><i class="icon-check"></i></span></p>
                            <h3>Always <br>Improving</h3>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 animate-box" data-animate-effect="fadeInLeft">
                <h2 class="colorlib-heading">History</h2>
                <p>On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would
                    have been rewritten a thousand times and everything that was left from its origin would be the word
                    "and" and the Little Blind Text should turn around and return to its own, safe country.</p>
            </div>
            <div class="col-md-8 animate-box" data-animate-effect="fadeInRight">
                <div class="fancy-collapse-panel">
                    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingOne">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"
                                        aria-expanded="true" aria-controls="collapseOne">Why choose me?
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                                <div class="panel-body">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <p>Far far away, behind the word mountains, far from the countries Vokalia
                                                and Consonantia, there live the blind texts. </p>
                                        </div>
                                        <div class="col-md-6">
                                            <p>Separated they live in Bookmarksgrove right at the coast of the
                                                Semantics, a large language ocean.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingTwo">
                                <h4 class="panel-title">
                                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"
                                        aria-expanded="false" aria-controls="collapseTwo">What I do?
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                                <div class="panel-body">
                                    <p>Far far away, behind the word <strong>mountains</strong>, far from the countries
                                        Vokalia and Consonantia, there live the blind texts. Separated they live in
                                        Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
                                    <ul>
                                        <li>Separated they live in Bookmarksgrove right</li>
                                        <li>Separated they live in Bookmarksgrove right</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading" role="tab" id="headingThree">
                                <h4 class="panel-title">
                                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree"
                                        aria-expanded="false" aria-controls="collapseThree">My Specialties
                                    </a>
                                </h4>
                            </div>
                            <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                                <div class="panel-body">
                                    <p>Far far away, behind the word <strong>mountains</strong>, far from the countries
                                        Vokalia and Consonantia, there live the blind texts. Separated they live in
                                        Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div id="colorlib-counter" class="colorlib-counters" style="background-image: url({% static 'images/cover_bg_1.jpg' %});"
    data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="colorlib-narrow-content">
        <div class="row">
        </div>
        <div class="row">
            <div class="col-md-3 text-center animate-box">
                <span class="icon"><i class="flaticon-skyline"></i></span>
                <span class="colorlib-counter js-counter" data-from="0" data-to="1539" data-speed="5000"
                    data-refresh-interval="50"></span>
                <span class="colorlib-counter-label">Projects</span>
            </div>
            <div class="col-md-3 text-center animate-box">
                <span class="icon"><i class="flaticon-engineer"></i></span>
                <span class="colorlib-counter js-counter" data-from="0" data-to="3653" data-speed="5000"
                    data-refresh-interval="50"></span>
                <span class="colorlib-counter-label">Employees</span>
            </div>
            <div class="col-md-3 text-center animate-box">
                <span class="icon"><i class="flaticon-architect-with-helmet"></i></span>
                <span class="colorlib-counter js-counter" data-from="0" data-to="5987" data-speed="5000"
                    data-refresh-interval="50"></span>
                <span class="colorlib-counter-label">Constructor</span>
            </div>
            <div class="col-md-3 text-center animate-box">
                <span class="icon"><i class="flaticon-worker"></i></span>
                <span class="colorlib-counter js-counter" data-from="0" data-to="3999" data-speed="5000"
                    data-refresh-interval="50"></span>
                <span class="colorlib-counter-label">Partners</span>
            </div>
        </div>
    </div>
</div>
{% endblock %}

gallery/templates/gallery/contact.html
{% extends 'base/main.html' %}

{% load staticfiles %}

{% block nav-bar %}
<nav id="colorlib-main-menu" role="navigation">
    <ul>
        <li><a href="{% url 'gallery:index' %}">Home</a></li>
        <li><a href="{% url 'gallery:projects' %}">Portfolio</a></li>
        <li><a href="{% url 'gallery:about' %}">About</a></li>
        <!-- <li><a href="">Services</a></li> -->
        <!-- <li><a href="blog.html">Blog</a></li> -->
        <li class="colorlib-active"><a href="{% url 'gallery:contact' %}">Contact</a></li>
    </ul>
</nav>
{% endblock %}

{% block content %}
    <div class="colorlib-contact">
        <div class="colorlib-narrow-content">
            <div class="row">
                <div class="col-md-12 animate-box" data-animate-effect="fadeInLeft">
                    <span class="heading-meta">Read</span>
                    <h2 class="colorlib-heading">Get in Touch</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-md-5">
                    <div class="colorlib-feature colorlib-feature-sm animate-box" data-animate-effect="fadeInLeft">
                        <div class="colorlib-icon">
                            <i class="icon-globe-outline"></i>
                        </div>
                        <div class="colorlib-text">
                            <p><a href="mailto:hussaynahq@gmail.com">hussaynahq@gmail.com</a></p>
                        </div>
                    </div>

                    <div class="colorlib-feature colorlib-feature-sm animate-box" data-animate-effect="fadeInLeft">
                        <div class="colorlib-icon">
                            <i class="icon-map"></i>
                        </div>
                        <div class="colorlib-text">
                            <p>Oko kan ni Sango</p>
                        </div>
                    </div>

                    <div class="colorlib-feature colorlib-feature-sm animate-box" data-animate-effect="fadeInLeft">
                        <div class="colorlib-icon">
                            <i class="icon-phone"></i>
                        </div>
                        <div class="colorlib-text">
                            <p><a href="tel://+2347065707149">+234 7065707149</a></p>
                        </div>
                    </div>
                </div>
                <div class="col-md-7 col-md-push-1">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1 col-md-pull-1 animate-box" data-animate-effect="fadeInLeft">
                            <form action="" method="post">{% csrf_token %}
                                {% for field in form.visible_fields %}
                                <div class="form-group">
                                    {{ field }}
                                </div>
                                {% endfor %}
                                <div class="form-group">
                                    <input type="submit" class="btn btn-primary btn-send-message" value="Send Message">
                                </div>
                            </form>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- <div id="map"></div>	 -->

    {% block contact %}
    {% endblock %}
{% endblock %}

gallery/templates/gallery/projects.html
{% extends 'base/main.html' %}

{% load staticfiles %}

{% block nav-bar %}
    <nav id="colorlib-main-menu" role="navigation">
        <ul>
            <li><a href="{% url 'gallery:index' %}">Home</a></li>
            <li class="colorlib-active"><a href="{% url 'gallery:projects' %}">Portfolio</a></li>
            <li><a href="{% url 'gallery:about' %}">About</a></li>
            <!-- <li><a href="">Services</a></li> -->
            <!-- <li><a href="blog.html">Blog</a></li> -->
            <li><a href="{% url 'gallery:contact' %}">Contact</a></li>
        </ul>
    </nav>
{% endblock %}

{% block content %}
    <div class="colorlib-work">
        <div class="colorlib-narrow-content">
            <div class="row">
                <div class="col-md-6 col-md-offset-3 col-md-pull-3 animate-box" data-animate-effect="fadeInLeft">
                    <span class="heading-meta">Portfolio</span>
                    <h2 class="colorlib-heading">My Works</h2>
                </div>
            </div>
            {% for design in object_list %}
                <div class="row row-bottom-padded-md">
                    <div class="{% cycle 'col-md-6' 'col-md-3' 'col-md-3' 'col-md-3' 'col-md-3' %} animate-box"
                        data-animate-effect="fadeInLeft">
                        <div class="project" style="background-image: url({{ design.pic.url }});">
                            <div class="desc">
                                <div class="con">
                                    <h3><a href="javascript:void(0)">{{ design.name }}</a></h3>
                                    <span>{{ design.get_design_type_display }}</span>
                                    {% comment %}
                                    <p class="icon">
                                        <span><a href="#"><i class="icon-share3"></i></a></span>
                                        <span><a href="#"><i class="icon-eye"></i> 100</a></span>
                                        <span><a href="#"><i class="icon-heart"></i> 49</a></span>
                                    </p>
                                    {% endcomment %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% if object_list|length >= 10 %}
                    {% if is_paginated %}
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                            <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                            {% else %}
                            <li class="disabled"><span>&laquo;</span></li>
                            {% endif %}
                            {% for i in paginator.page_range %}
                            {% if page_obj.number == i %}
                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                            {% else %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                            <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                            {% else %}
                            <li class="disabled"><span>&raquo;</span></li>
                            {% endif %}
                    </ul>
                    {% endif %}
                {% endif %}           
            {% empty %}
            <div class="row row-bottom-padded-md">
                <div class="col-md-6 animate-box" data-animate-effect="fadeInLeft">
                    <div class="project" style="background-image: url({% static 'images/img-1.jpg' %});">
                        <div class="desc">
                            <div class="con">
                                <h3><a href="javascript:void(0)">Work 01</a></h3>
                                <span>Building</span>
                                <!-- <p class="icon">
                                    <span><a href="#"><i class="icon-share3"></i></a></span>
                                    <span><a href="#"><i class="icon-eye"></i> 100</a></span>
                                    <span><a href="#"><i class="icon-heart"></i> 49</a></span>
                                </p> -->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 animate-box" data-animate-effect="fadeInLeft">
                    <div class="project" style="background-image: url({% static 'images/img-2.jpg' %});">
                        <div class="desc">
                            <div class="con">
                                <h3><a href="javascript:void(0)">Work 02</a></h3>
                                <span>House, Apartment</span>
                                <!-- <p class="icon">
                                    <span><a href="#"><i class="icon-share3"></i></a></span>
                                    <span><a href="#"><i class="icon-eye"></i> 100</a></span>
                                    <span><a href="#"><i class="icon-heart"></i> 49</a></span>
                                </p> -->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 animate-box" data-animate-effect="fadeInLeft">
                    <div class="project" style="background-image: url({% static 'images/img-3.jpg' %});">
                        <div class="desc">
                            <div class="con">
                                <h3><a href="javascript:void(0)">Work 03</a></h3>
                                <span>Dining Room</span>
                                <!-- <p class="icon">
                                    <span><a href="#"><i class="icon-share3"></i></a></span>
                                    <span><a href="#"><i class="icon-eye"></i> 100</a></span>
                                    <span><a href="#"><i class="icon-heart"></i> 49</a></span>
                                </p> -->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 animate-box" data-animate-effect="fadeInLeft">
                    <div class="project" style="background-image: url({% static 'images/img-4.jpg' %});">
                        <div class="desc">
                            <div class="con">
                                <h3><a href="javascript:void(0)">Work 04</a></h3>
                                <span>House, Building</span>
                                <!-- <p class="icon">
                                    <span><a href="#"><i class="icon-share3"></i></a></span>
                                    <span><a href="#"><i class="icon-eye"></i> 100</a></span>
                                    <span><a href="#"><i class="icon-heart"></i> 49</a></span>
                                </p> -->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 animate-box" data-animate-effect="fadeInLeft">
                    <div class="project" style="background-image: url({% static 'images/img-5.jpg' %});">
                        <div class="desc">
                            <div class="con">
                                <h3><a href="javascript:void(0)">Work 05</a></h3>
                                <span>Condo, Pad</span>
                                <!-- <p class="icon">
                                    <span><a href="#"><i class="icon-share3"></i></a></span>
                                    <span><a href="#"><i class="icon-eye"></i> 100</a></span>
                                    <span><a href="#"><i class="icon-heart"></i> 49</a></span>
                                </p> -->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 animate-box" data-animate-effect="fadeInLeft">
                    <div class="project" style="background-image: url({% static 'images/img-6.jpg' %});">
                        <div class="desc">
                            <div class="con">
                                <h3><a href="javascript:void(0)">Work 06</a></h3>
                                <span>Table, Chairs</span>
                                <!-- <p class="icon">
                                    <span><a href="#"><i class="icon-share3"></i></a></span>
                                    <span><a href="#"><i class="icon-eye"></i> 100</a></span>
                                    <span><a href="#"><i class="icon-heart"></i> 49</a></span>
                                </p> -->
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-3 animate-box" data-animate-effect="fadeInLeft">
                    <div class="project" style="background-image: url({% static 'images/img-7.jpg' %});">
                        <div class="desc">
                            <div class="con">
                                <h3><a href="javascript:void(0)">Work 02</a></h3>
                                <span>House, Apartment</span>
                                <!-- <p class="icon">
                                    <span><a href="#"><i class="icon-share3"></i></a></span>
                                    <span><a href="#"><i class="icon-eye"></i> 100</a></span>
                                    <span><a href="#"><i class="icon-heart"></i> 49</a></span>
                                </p> -->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 animate-box" data-animate-effect="fadeInLeft">
                    <div class="project" style="background-image: url({% static 'images/img-8.jpg' %});">
                        <div class="desc">
                            <div class="con">
                                <h3><a href="javascript:void(0)">Work 03</a></h3>
                                <span>Dining Room</span>
                                <!-- <p class="icon">
                                    <span><a href="#"><i class="icon-share3"></i></a></span>
                                    <span><a href="#"><i class="icon-eye"></i> 100</a></span>
                                    <span><a href="#"><i class="icon-heart"></i> 49</a></span>
                                </p> -->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 animate-box" data-animate-effect="fadeInLeft">
                    <div class="project" style="background-image: url({% static 'images/img-9.jpg' %});">
                        <div class="desc">
                            <div class="con">
                                <h3><a href="javascript:void(0)">Work 04</a></h3>
                                <span>House, Building</span>
                                <!-- <p class="icon">
                                    <span><a href="#"><i class="icon-share3"></i></a></span>
                                    <span><a href="#"><i class="icon-eye"></i> 100</a></span>
                                    <span><a href="#"><i class="icon-heart"></i> 49</a></span>
                                </p> -->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 animate-box" data-animate-effect="fadeInLeft">
                    <div class="project" style="background-image: url({% static 'images/img-5.jpg' %});">
                        <div class="desc">
                            <div class="con">
                                <h3><a href="javascript:void(0)">Work 05</a></h3>
                                <span>Condo, Pad</span>
                                <!-- <p class="icon">
                                    <span><a href="#"><i class="icon-share3"></i></a></span>
                                    <span><a href="#"><i class="icon-eye"></i> 100</a></span>
                                    <span><a href="#"><i class="icon-heart"></i> 49</a></span>
                                </p> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endfor %}
{% endblock %}

serenitys_gallery/templates/base/message_display.html
{% if messages %}
    <div class="row">
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger">
                    {{ message|safe }}
                </div>
                {% else %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message|safe }}
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endif %}